"""
Incubator Metrics Configuration
Based on academic research and literature analysis
"""
from typing import List, Dict, Any

# Priority-based metrics from the research
INCUBATOR_METRICS = {
    "critical": [
        {
            "metric_id": "METRIC_001",
            "name": "Average Jobs per Tenant",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Average number of jobs created per tenant company",
            "unit": "jobs/tenant",
            "benchmark": 4.6,
            "weight": 0.0634,
            "crawling_strategy": ["annual_reports", "government_portals", "linkedin_company_pages"],
            "validation_sources": ["crunchbase", "tracxn", "news_articles"]
        },
        {
            "metric_id": "METRIC_002",
            "name": "Survival Rate",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Percentage of incubatee companies that survive after graduation",
            "unit": "percentage",
            "benchmark": 86.0,
            "weight": 0.0585,
            "crawling_strategy": ["crunchbase_tracking", "company_registry", "follow_up_surveys"],
            "validation_sources": ["business_registries", "tax_records", "websites"]
        },
        {
            "metric_id": "METRIC_005",
            "name": "Funds Attracted",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Total funding raised by incubatee companies",
            "unit": "millions USD",
            "benchmark": 353.9,
            "weight": 0.0341,
            "crawling_strategy": ["crunchbase_api", "tracxn_api", "venturebeat", "techcrunch"],
            "validation_sources": ["SEC_filings", "company_announcements", "press_releases"]
        },
        {
            "metric_id": "METRIC_022",
            "name": "Graduation Rate",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Rate at which incubatee companies graduate from the program",
            "unit": "percentage",
            "benchmark": 75.0,
            "weight": 0.045,
            "crawling_strategy": ["graduation_ceremonies", "alumni_lists", "program_statistics"],
            "validation_sources": ["incubator_reports", "follow_up_studies"]
        }
    ],
    "high": [
        {
            "metric_id": "METRIC_003",
            "name": "Number of Incubatees",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Total number of companies currently in incubation",
            "unit": "count",
            "benchmark": 35.0,
            "weight": 0.0390,
            "crawling_strategy": ["incubator_website", "annual_reports", "member_directories"],
            "validation_sources": ["direct_inquiry", "published_roster"]
        },
        {
            "metric_id": "METRIC_004",
            "name": "Revenue Generated",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Total revenue generated by all incubatee companies",
            "unit": "millions USD",
            "benchmark": 55.1,
            "weight": 0.0366,
            "crawling_strategy": ["annual_reports", "news_articles", "financial_disclosures"],
            "validation_sources": ["crunchbase", "company_websites", "industry_reports"]
        },
        {
            "metric_id": "METRIC_011",
            "name": "Patents Granted",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Number of patents granted to incubatee companies annually",
            "unit": "count/year",
            "benchmark": 2.0,
            "weight": 0.0146,
            "crawling_strategy": ["USPTO_api", "WIPO_database", "google_patents"],
            "validation_sources": ["patent_assignments", "company_IP_portfolios"]
        },
        {
            "metric_id": "METRIC_014",
            "name": "Equity Investment",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Total equity investment received by incubatees",
            "unit": "millions USD",
            "benchmark": 62.8,
            "weight": 0.0098,
            "crawling_strategy": ["crunchbase", "pitchbook", "venture_capital_directories"],
            "validation_sources": ["investment_rounds", "company_disclosures"]
        },
        {
            "metric_id": "METRIC_017",
            "name": "Reputation Score",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Student and industry perception of incubation center",
            "unit": "scale (1-5)",
            "benchmark": 4.00,
            "weight": 0.020,
            "crawling_strategy": ["student_reviews", "social_sentiment_analysis", "alumni_feedback"],
            "validation_sources": ["survey_data", "testimonials"]
        },
        {
            "metric_id": "METRIC_018",
            "name": "Education Integration",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Integration of education with incubation activities",
            "unit": "scale (1-5)",
            "benchmark": 4.28,
            "weight": 0.025,
            "crawling_strategy": ["curriculum_analysis", "partnership_announcements", "joint_events"],
            "validation_sources": ["institutional_documents", "collaboration_agreements"]
        }
    ],
    "medium": [
        {
            "metric_id": "METRIC_006",
            "name": "Sales Growth",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Percentage growth in sales of incubatee companies",
            "unit": "percentage",
            "benchmark": 28.1,
            "weight": 0.0317,
            "crawling_strategy": ["financial_reports", "company_websites", "industry_analyses"],
            "validation_sources": ["company_disclosures", "market_research"]
        },
        {
            "metric_id": "METRIC_007",
            "name": "Network Size",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Number of total connections in the incubator's network",
            "unit": "count",
            "benchmark": 189.0,
            "weight": 0.0317,
            "crawling_strategy": ["linkedin_api", "website_scraping", "event_participant_lists"],
            "validation_sources": ["partnership_announcements", "network_directories"]
        },
        {
            "metric_id": "METRIC_009",
            "name": "Average Incubation Time",
            "type": "numerical",
            "higher_is_better": False,
            "description": "Average duration companies stay in incubation (lower is better)",
            "unit": "months",
            "benchmark": 30.0,
            "weight": 0.0244,
            "crawling_strategy": ["graduation_records", "annual_reports", "program_documents"],
            "validation_sources": ["alumni_tracking", "program_catalogs"]
        },
        {
            "metric_id": "METRIC_020",
            "name": "Mentor Quality",
            "type": "numerical",
            "higher_is_better": True,
            "description": "Quality and effectiveness of mentoring services",
            "unit": "scale (1-5)",
            "benchmark": 4.13,
            "weight": 0.022,
            "crawling_strategy": ["mentor_profiles", "student_feedback", "mentor_credentials"],
            "validation_sources": ["mentor_directories", "mentee_testimonials"]
        }
    ]
}

def get_all_incubator_metrics() -> List[Dict[str, Any]]:
    """Get all incubator metrics flattened"""
    all_metrics = []
    for priority in ["critical", "high", "medium"]:
        all_metrics.extend(INCUBATOR_METRICS[priority])
    return all_metrics

def get_top_metrics(top_n: int = 10) -> List[Dict[str, Any]]:
    """Get top N metrics by weight"""
    all_metrics = get_all_incubator_metrics()
    sorted_metrics = sorted(all_metrics, key=lambda x: x["weight"], reverse=True)
    return sorted_metrics[:top_n]

def get_metrics_by_priority(priority: str) -> List[Dict[str, Any]]:
    """Get metrics by priority level"""
    return INCUBATOR_METRICS.get(priority, [])

def format_metric_for_llm(metric: Dict[str, Any]) -> Dict[str, Any]:
    """Format metric for LLM consumption"""
    return {
        "name": metric["name"],
        "type": metric["type"],
        "higher_is_better": metric["higher_is_better"],
        "description": metric["description"],
        "unit": metric.get("unit", ""),
        "benchmark": metric.get("benchmark", 0)
    }